let V=[];
const app=document.querySelector('#app');
const $=s=>document.querySelector(s);
const DATA_URL='https://raw.githubusercontent.com/mongayesluina/verb-quest/data-snapshot/index.html';
const saved=(()=>{try{return JSON.parse(localStorage.vqFull||'{}')}catch{return{}}})();
let state={score:+(saved.score||0),streak:+(saved.streak||0),level:saved.level??1,mode:saved.mode||'level',custom:Array.isArray(saved.custom)?saved.custom:[],sound:saved.sound!==false};
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const sample=(a,n)=>shuffle(a).slice(0,Math.min(n,a.length));
const primary=v=>v[1].split('/')[0].trim();
const pastForms=v=>v[1].split('/').map(x=>x.trim().toLowerCase());
const enc=s=>encodeURIComponent(String(s));
function save(){localStorage.vqFull=JSON.stringify(state);topbar()}
function topbar(){if(!V.length)return;$('#score').textContent=state.score;$('#streak').textContent=state.streak;$('#modeChip').textContent=state.mode==='custom'?`Teacher • ${state.custom.length}`:state.level===0?`All • ${V.length}`:`Level ${state.level} • ${pool().length}`}
function pool(){if(state.mode==='custom'&&state.custom.length>=4){let s=new Set(state.custom);return V.filter((v,i)=>s.has(i))}return state.level===0?V:V.filter(v=>v[4]===state.level)}
function add(n){state.score+=n;state.streak++;save()}
function miss(){state.streak=0;save()}
function speak(t){if(state.sound&&'speechSynthesis'in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=.88;speechSynthesis.speak(u)}}
function icon(v){return v[6]||'🎯'}
function typ(v){return v[5]==='i'?'Irregular':'Regular'}
function head(title,sub=''){return `<div class="sectionHead"><div><button class="back" onclick="home()">← Home</button><h1>${title}</h1>${sub?`<p class="muted">${sub}</p>`:''}</div></div>`}
async function load(){try{let t=await fetch(DATA_URL+'?v=2').then(r=>{if(!r.ok)throw Error(r.status);return r.text()});let m=t.match(/const V=(\[[\s\S]*?\]);let score=/);if(!m)throw Error('Verb data not found');V=Function('"use strict";return ('+m[1]+')')();topbar();home()}catch(e){app.innerHTML=`<div class="loading"><div class="spin">⚠️</div><h2>Could not load the verb list</h2><p class="muted">Check your Internet connection and reload the page.</p><button class="btn primary" onclick="location.reload()">Reload</button></div>`}}
function home(){let cards=[
['flash','🎴','Flashcards','Study all four forms and listen to pronunciation.','#6557ff','#9678ff',''],
['quiz','🧩','Past Challenge','Mixed questions: past, base, meaning and typing.','#ff6aa9','#ff9f6a','HARDER'],
['memory','🧠','Memory Pro','More pairs and less room for guessing.','#2bb7a1','#5bd8b2','HARDER'],
['robot','🤖','Save the Robot','Only two mistakes. Miss twice and the robot powers down.','#ff8357','#ff4f76','2 LIVES'],
['matchGame','🔗','Match Rush','Match eight verb pairs correctly.','#3f9cff','#63d1ff','8 PAIRS'],
['drawGame','🎨','Draw & Spell','Draw the action, then type the past form to score.','#a75cff','#ec6fe7','HARDER'],
['ladderGame','🪜','Verb Ladder','Climb base → past → participle → meaning.','#19b87c','#7bd36d','NEW'],
['speedGame','⚡','Speed Run','45 seconds. Type as many past forms as you can.','#ffb21d','#ff6a43','NEW'],
['finalGame','🏆','Final Challenge','15 mixed questions with a complete review.','#232d52','#6557ff','15 Q']
];
app.innerHTML=`<section class="hero"><div><div class="eyebrow">200 verbs • 9 games • classroom ready</div><h1>Master the past through <span>challenge and play.</span></h1><p>Practice regular and irregular verbs with memory, spelling, matching, speed, listening and mixed challenges. Choose a level or create your own classroom set.</p><div class="row"><button class="btn primary" onclick="levels()">Choose a level</button><button class="btn secondary" onclick="teacher()">Teacher Mode</button><button class="btn darkBtn" onclick="finalGame()">🏆 Final Challenge</button></div></div><div class="heroArt"><span class="orb one"></span><span class="orb two"></span><div class="heroCard"><div><div class="e">🏃</div><b>RUN → RAN</b><div class="muted" style="margin-top:5px">ready to play?</div></div></div></div></section><div class="sectionTitle"><div><h2>Game zone</h2><p>Games now become more demanding as you progress.</p></div><span class="chip">9 GAMES</span></div><section class="games">${cards.map(c=>`<button class="game ${c[6]==='NEW'?'new':''}" style="--c1:${c[4]};--c2:${c[5]}" onclick="${c[0]}()"><div class="i">${c[1]}</div>${c[6]?`<span class="tag">${c[6]}</span>`:''}<h3>${c[2]}</h3><p>${c[3]}</p></button>`).join('')}</section>`;topbar()}
function levels(){let meta=[[1,'Essentials','70 high-frequency verbs. Best place to begin.'],[2,'Everyday English','70 verbs for stories and conversation.'],[3,'Challenge','60 less predictable verbs and spelling forms.'],[0,'All 200','Mix every regular and irregular verb.']];app.innerHTML=head('Choose a level','The selected level controls every game.')+`<div class="levelGrid">${meta.map(m=>`<button class="level ${state.mode==='level'&&state.level===m[0]?'active':''}" onclick="setLevel(${m[0]})"><span class="num">${m[0]||'∞'}</span><h3>${m[1]}</h3><p class="muted">${m[2]}</p><b>${m[0]===0?200:V.filter(v=>v[4]===m[0]).length} verbs →</b></button>`).join('')}</div>`}
function setLevel(n){state.level=n;state.mode='level';save();home()}
let teacherSet=new Set();
function teacher(){teacherSet=new Set(state.mode==='custom'?state.custom:pool().map(v=>V.indexOf(v)));app.innerHTML=head('Teacher Mode','Select at least four verbs. Every game will use the same set.')+`<div class="toolbar"><input id="search" placeholder="Search: go, went, ir..." oninput="teacherList()"><select id="lev" onchange="teacherList()"><option value="0">All levels</option><option value="1">Level 1</option><option value="2">Level 2</option><option value="3">Level 3</option></select><select id="tp" onchange="teacherList()"><option value="a">All types</option><option value="i">Irregular</option><option value="r">Regular</option></select></div><div class="teacherButtons"><button class="btn secondary small" onclick="pickType('i')">All irregular</button><button class="btn secondary small" onclick="pickType('r')">All regular</button><button class="btn secondary small" onclick="pickAll()">All 200</button><button class="btn danger small" onclick="teacherSet.clear();teacherList()">Clear</button><button class="btn primary small" onclick="useTeacher()">Use selected (<span id="selCount">0</span>)</button></div><div class="verbGrid" id="verbGrid"></div>`;teacherList()}
function teacherList(){let q=($('#search')?.value||'').toLowerCase(),l=+($('#lev')?.value||0),t=$('#tp')?.value||'a';let out=[];V.forEach((v,i)=>{if((!q||[v[0],v[1],v[2],v[3]].join(' ').toLowerCase().includes(q))&&(!l||v[4]===l)&&(t==='a'||v[5]===t))out.push([v,i])});$('#verbGrid').innerHTML=out.map(([v,i])=>`<label class="verbItem ${teacherSet.has(i)?'checked':''}"><input type="checkbox" ${teacherSet.has(i)?'checked':''} onchange="toggleVerb(${i},this.checked)"><span><strong>${v[0]} → ${v[1]}</strong><small>${v[3]} • ${typ(v)} • L${v[4]}</small></span></label>`).join('');$('#selCount').textContent=teacherSet.size}
function toggleVerb(i,on){on?teacherSet.add(i):teacherSet.delete(i);teacherList()}
function pickType(t){teacherSet=new Set(V.map((v,i)=>v[5]===t?i:null).filter(i=>i!==null));teacherList()}
function pickAll(){teacherSet=new Set(V.map((_,i)=>i));teacherList()}
function useTeacher(){if(teacherSet.size<4)return alert('Select at least 4 verbs.');state.custom=[...teacherSet];state.mode='custom';save();home()}
let fi=0;
function flash(){let a=pool();fi%=a.length;let v=a[fi];app.innerHTML=head('Flashcards','Study all four forms, then say them aloud.')+`<div class="panel flash"><div class="picture"><div><div class="big">${icon(v)}</div><span class="chip">${typ(v)} • Level ${v[4]}</span></div></div><div class="word"><div class="muted">BASE FORM</div><h2>${v[0]}</h2><p class="muted">${v[3]}</p><div class="past">${v[1]}</div><div class="forms"><div><small class="muted">PAST PARTICIPLE</small><br><b>${v[2]}</b></div><div><small class="muted">TYPE</small><br><b>${typ(v)}</b></div></div><div class="row"><button class="btn primary" onclick="speak('${v[0].replace(/'/g,"\\'")}');setTimeout(()=>speak('${primary(v).replace(/'/g,"\\'")}'),650)">🔊 Base + Past</button><button class="btn secondary" onclick="fi=(fi-1+pool().length)%pool().length;flash()">← Previous</button><button class="btn secondary" onclick="fi=(fi+1)%pool().length;flash()">Next →</button></div></div></div>`}
function quiz(){let round=Array.from({length:12},()=>sample(pool(),1)[0]),i=0,good=0,bad=[];function next(){if(i>=round.length){let pct=Math.round(good/round.length*100);app.innerHTML=head('Past Challenge')+`<div class="panel result"><div style="font-size:72px">${pct>=85?'🏆':pct>=65?'⭐':'📚'}</div><div class="score">${good}/12</div><h2>${pct}% accuracy</h2><p class="muted">This round mixed four different question types.</p>${bad.length?`<div class="review">${bad.map(x=>`<div><span>${x[0].toUpperCase()}</span><b>${x[1].toUpperCase()}</b></div>`).join('')}</div>`:''}<button class="btn primary" onclick="quiz()">Play another round</button></div>`;return}let v=round[i],type=i%4,body='';if(type===0){let ans=primary(v),opts=shuffle([ans,...sample(V.filter(x=>primary(x)!==ans),3).map(primary)]);body=choiceBlock(v,`Choose the past simple of ${v[0].toUpperCase()}`,opts,ans)}else if(type===1){let ans=v[0],opts=shuffle([ans,...sample(V.filter(x=>x[0]!==ans),3).map(x=>x[0])]);body=`<div class="finalBig">${primary(v)}</div><h2>Which base form matches this past?</h2>`+choiceOptions(opts,ans)}else if(type===2){let ans=v[3],opts=shuffle([ans,...sample(V.filter(x=>x[3]!==ans),3).map(x=>x[3])]);body=`<div class="picture"><div><div class="big">${icon(v)}</div><div class="finalBig" style="font-size:40px">${v[0]}</div></div></div><h2>Choose the Spanish meaning:</h2>`+choiceOptions(opts,ans,false)}else{body=`<div class="picture"><div><div class="big">${icon(v)}</div><h2>${v[0].toUpperCase()}</h2><p class="muted">${v[3]}</p></div></div><h2>Type the past simple:</h2><div class="row"><input id="typedQuiz" class="answerInput" autocomplete="off" placeholder="Type the past form"><button class="btn primary" onclick="checkTypedQuiz()">Check</button></div>`}app.innerHTML=head('Past Challenge',`Question ${i+1} / 12 • ${good} correct`)+`<div class="panel quiz"><div class="progress"><span style="width:${i/12*100}%"></span></div><div style="height:15px"></div>${body}<div id="feed" class="feedback"></div></div>`;window.qz={v,type,good:()=>good++,bad:()=>bad.push(v),next:()=>{i++;next()}};if(type===3)setTimeout(()=>$('#typedQuiz')?.focus(),50)}next()}
function choiceBlock(v,title,opts,ans){return `<div class="picture"><div><div class="big">${icon(v)}</div><h2>${v[0].toUpperCase()}</h2><span class="muted">${v[3]}</span></div></div><h2>${title}</h2>${choiceOptions(opts,ans)}`}
