const enc=s=>encodeURIComponent(String(s));
let explorerIndex=0;

function verbExplorer(){
  const a=pool();explorerIndex=(explorerIndex+a.length)%a.length;const v=a[explorerIndex];const c=Grammar.context(v);
  const presentExample=Grammar.affirmative(v,'present',c.subject,true);
  const pastExample=Grammar.affirmative(v,'past',c.subject,true);
  app.innerHTML=head('Verb Explorer','Study the complete verb before you play.')+`<div class="panel studyCard"><div class="studyVisual"><div class="studyEmoji">${icon(v)}</div><span class="chip">${typeName(v)} • Level ${v.level}</span><h2>${escapeHtml(v.meaning)}</h2></div><div class="studyBody"><div class="verbHeadline"><span class="eyebrow">BASE FORM</span><h2>${escapeHtml(v.base)}</h2></div><div class="formGrid"><div><small>I / YOU / WE / THEY</small><b>${escapeHtml(Grammar.present(v,'They'))}</b><span>Present simple</span></div><div><small>HE / SHE / IT</small><b>${escapeHtml(Grammar.present(v,'She'))}</b><span>Present simple</span></div><div><small>PAST</small><b>${escapeHtml(v.base==='be'?'was / were':v.past)}</b><span>Past simple</span></div><div><small>PARTICIPLE</small><b>${escapeHtml(v.participle)}</b><span>Past participle</span></div></div><div class="exampleBox presentExample"><span class="tenseBadge presentBadge">PRESENT</span><p>${escapeHtml(presentExample)}</p></div><div class="exampleBox pastExample"><span class="tenseBadge pastBadge">PAST</span><p>${escapeHtml(pastExample)}</p></div><div class="grammarMini"><div><b>Negative:</b> ${escapeHtml(Grammar.negative(v,'past',c.subject,true))}</div><div><b>Question:</b> ${escapeHtml(Grammar.question(v,'past',c.subject,true))}</div></div><div class="row"><button class="btn primary" onclick="speak('${v.base.replace(/'/g,"\\'")}');setTimeout(()=>speak('${primaryPast(v).replace(/'/g,"\\'")}'),700)">🔊 Listen</button><button class="btn secondary" onclick="explorerIndex--;verbExplorer()">← Previous</button><button class="btn secondary" onclick="explorerIndex++;verbExplorer()">Next →</button></div></div></div>`;
}

function tenseChoice(){
  const round=Array.from({length:12},()=>sample(sentencePool(),1)[0]);let i=0,good=0;
  function render(){
    if(i>=round.length){const pct=Math.round(good/round.length*100);app.innerHTML=head('Present or Past?')+resultCard(good,round.length,pct,'tenseChoice()');return;}
    const v=round[i],tense=Math.random()<.5?'present':'past';const subjects=['I','You','He','She','We','They'];const subject=sample(subjects,1)[0];const correct=tense==='present'?Grammar.present(v,subject):Grammar.past(v,subject);const marker=tense==='present'?'every day':'yesterday';
    let options=[correct,...(tense==='present'?Grammar.presentOptions(v,subject):Grammar.pastOptions(v,subject))].filter((x,idx,arr)=>arr.indexOf(x)===idx);while(options.length<4){const other=sample(V,1)[0];options.push(tense==='present'?Grammar.present(other,subject):Grammar.past(other,subject));options=[...new Set(options)]}options=shuffle(options).slice(0,4);
    const c=Grammar.context(v);const sentence=`${subject} ____ ${c.complement} ${marker}.`;
    app.innerHTML=head('Present or Past?',`Question ${i+1} / ${round.length} • Read the time expression carefully.`)+`<div class="panel quiz"><div class="progress"><span style="width:${i/round.length*100}%"></span></div><div class="tensePrompt"><span class="tenseBadge ${tense==='present'?'presentBadge':'pastBadge'}">${tense.toUpperCase()}</span><div class="promptEmoji">${icon(v)}</div><h2>${escapeHtml(sentence)}</h2><p class="muted">${escapeHtml(v.meaning)}</p></div><div class="options">${options.map(o=>`<button class="option" onclick="checkTenseChoice(this,decodeURIComponent('${enc(o)}'),decodeURIComponent('${enc(correct)}'))">${escapeHtml(o)}</button>`).join('')}</div><div id="feed" class="feedback"></div></div>`;
    window.tenseRound={good:()=>good++,next:()=>{i++;render()}};
  }
  render();
}
function checkTenseChoice(button,answer,correct){document.querySelectorAll('.option').forEach(x=>x.disabled=true);if(answer===correct){button.classList.add('ok');$('#feed').textContent='Correct! +10 XP';$('#feed').style.color='var(--green)';addXP(10);window.tenseRound.good()}else{button.classList.add('bad');[...document.querySelectorAll('.option')].find(x=>x.textContent===correct)?.classList.add('ok');$('#feed').textContent='Correct answer: '+correct;$('#feed').style.color='var(--red)';resetStreak()}setTimeout(window.tenseRound.next,850)}

function fillSentence(){
  const round=Array.from({length:10},()=>sample(sentencePool(),1)[0]);let i=0,good=0;
  function render(){
    if(i>=round.length){app.innerHTML=head('Fill the Sentence')+resultCard(good,round.length,Math.round(good/round.length*100),'fillSentence()');return;}
    const v=round[i],tense=Math.random()<.5?'present':'past',subject=sample(Grammar.SUBJECTS,1)[0],c=Grammar.context(v),correct=tense==='present'?Grammar.present(v,subject):Grammar.past(v,subject),marker=tense==='present'?'every day':'yesterday';
    app.innerHTML=head('Fill the Sentence',`Question ${i+1} / ${round.length} • Type the correct verb form.`)+`<div class="panel finalBox"><div class="tensePrompt"><span class="tenseBadge ${tense==='present'?'presentBadge':'pastBadge'}">${tense.toUpperCase()}</span><div class="promptEmoji">${icon(v)}</div><h2>${escapeHtml(subject)} <span class="blankWord">______</span> ${escapeHtml(c.complement)} ${marker}.</h2><p class="muted">Verb: <b>${escapeHtml(v.base)}</b> • ${escapeHtml(v.meaning)}</p></div><div class="answerRow"><input id="fillInput" class="answerInput bigInput" autocomplete="off" placeholder="Type the verb"><button class="btn primary" onclick="checkFillSentence()">Check</button></div><div id="feed" class="feedback"></div></div>`;
    window.fillRound={v,correct,good:()=>good++,next:()=>{i++;render()}};const input=$('#fillInput');input.focus();input.onkeydown=e=>{if(e.key==='Enter')checkFillSentence()};
  }
  render();
}
function checkFillSentence(){const r=window.fillRound,input=$('#fillInput');if(input.disabled)return;const val=input.value.trim().toLowerCase();input.disabled=true;if(val===r.correct.toLowerCase()||(r.v.base==='be'&&pastForms(r.v).includes(val))){$('#feed').textContent='Correct! +12 XP';$('#feed').style.color='var(--green)';addXP(12);r.good()}else{$('#feed').textContent='Correct answer: '+r.correct;$('#feed').style.color='var(--red)';resetStreak()}setTimeout(r.next,900)}

function sentenceBuilder(){
  const rounds=Array.from({length:8},()=>sample(sentencePool(),1)[0]);let i=0,good=0;
  function next(){
    if(i>=rounds.length){app.innerHTML=head('Build the Sentence')+resultCard(good,rounds.length,Math.round(good/rounds.length*100),'sentenceBuilder()');return;}
    const v=rounds[i],tense=Math.random()<.5?'present':'past';let kind='affirmative';if(state.level>=2&&Math.random()<.35)kind=Math.random()<.5?'negative':'question';const c=Grammar.context(v);const target=Grammar[kind](v,tense,c.subject,true);const tokens=Grammar.tokenize(target).map((text,index)=>({text,index,key:index+'-'+Math.random()}));window.builder={target,tokens:shuffle(tokens),chosen:[],good:()=>good++,next:()=>{i++;next()},tense,kind,v};renderBuilder(i,rounds.length);
  }
  next();
}
function renderBuilder(i,total){const b=window.builder;const label=b.kind==='affirmative'?'Affirmative':b.kind==='negative'?'Negative':'Question';app.innerHTML=head('Build the Sentence',`Sentence ${i+1} / ${total} • ${label} • ${b.tense==='present'?'Present':'Past'}`)+`<div class="panel builderPanel"><div class="builderHint"><span class="tenseBadge ${b.tense==='present'?'presentBadge':'pastBadge'}">${b.tense.toUpperCase()}</span><span class="chip">${label.toUpperCase()}</span><span class="chip">${icon(b.v)} ${escapeHtml(b.v.base)} = ${escapeHtml(b.v.meaning)}</span></div><div id="builtSentence" class="builtSentence">${b.chosen.length?b.chosen.map(x=>`<button onclick="removeBuilderWord('${x.key}')">${escapeHtml(x.text)}</button>`).join(''):'<span>Tap words below to build the sentence</span>'}</div><div class="wordBank">${b.tokens.map(x=>`<button onclick="addBuilderWord('${x.key}')">${escapeHtml(x.text)}</button>`).join('')}</div><div class="row"><button class="btn primary" onclick="checkBuilder()">Check sentence</button><button class="btn secondary" onclick="resetBuilder()">Reset</button></div><div id="feed" class="feedback"></div></div>`}
function addBuilderWord(key){const b=window.builder,idx=b.tokens.findIndex(x=>x.key===key);if(idx<0)return;b.chosen.push(b.tokens.splice(idx,1)[0]);renderBuilder(parseInt((document.querySelector('.sectionHead p')?.textContent.match(/\d+/)||['1'])[0])-1||0,8)}
function removeBuilderWord(key){const b=window.builder,idx=b.chosen.findIndex(x=>x.key===key);if(idx<0)return;b.tokens.push(b.chosen.splice(idx,1)[0]);renderBuilder(0,8)}
function resetBuilder(){const b=window.builder;b.tokens=shuffle([...b.tokens,...b.chosen]);b.chosen=[];renderBuilder(0,8)}
function checkBuilder(){const b=window.builder,answer=b.chosen.map(x=>x.text).join(' ');if(Grammar.sameSentence(answer,b.target)){const feed=$('#feed');feed.textContent='Excellent! '+b.target;feed.style.color='var(--green)';addXP(15);b.good();setTimeout(b.next,1000)}else{const feed=$('#feed');feed.textContent='Not yet. Check word order, auxiliary and verb form.';feed.style.color='var(--red)';resetStreak()}}

function transformTense(){
  const round=Array.from({length:8},()=>sample(sentencePool(),1)[0]);let i=0,good=0;
  function render(){
    if(i>=round.length){app.innerHTML=head('Change the Tense')+resultCard(good,round.length,Math.round(good/round.length*100),'transformTense()');return;}
    const v=round[i],from=Math.random()<.5?'present':'past',to=from==='present'?'past':'present',c=Grammar.context(v),source=Grammar.affirmative(v,from,c.subject,true),target=Grammar.affirmative(v,to,c.subject,true);
    app.innerHTML=head('Change the Tense',`Sentence ${i+1} / ${round.length} • Rewrite the complete sentence.`)+`<div class="panel finalBox"><div class="transformBox"><span class="tenseBadge ${from==='present'?'presentBadge':'pastBadge'}">${from.toUpperCase()}</span><p class="sourceSentence">${escapeHtml(source)}</p><div class="transformArrow">↓</div><span class="tenseBadge ${to==='present'?'presentBadge':'pastBadge'}">CHANGE TO ${to.toUpperCase()}</span></div><textarea id="transformInput" class="sentenceInput" rows="3" placeholder="Write the complete sentence"></textarea><button class="btn primary" onclick="checkTransform()">Check sentence</button><div id="feed" class="feedback"></div></div>`;
    window.transformRound={target,good:()=>good++,next:()=>{i++;render()}};$('#transformInput').focus();
  }
  render();
}
function checkTransform(){const r=window.transformRound,input=$('#transformInput');if(input.disabled)return;input.disabled=true;if(Grammar.sameSentence(input.value,r.target)){$('#feed').innerHTML=`Correct! <b>${escapeHtml(r.target)}</b>`;$('#feed').style.color='var(--green)';addXP(18);r.good()}else{$('#feed').innerHTML=`Correct sentence: <b>${escapeHtml(r.target)}</b>`;$('#feed').style.color='var(--red)';resetStreak()}setTimeout(r.next,1400)}

function grammarLab(){
  const round=Array.from({length:10},()=>sample(sentencePool(),1)[0]);let i=0,good=0;
  function render(){
    if(i>=round.length){app.innerHTML=head('Grammar Lab')+resultCard(good,round.length,Math.round(good/round.length*100),'grammarLab()');return;}
    const v=round[i],tense=Math.random()<.5?'present':'past',kind=Math.random()<.5?'negative':'question',c=Grammar.context(v),source=Grammar.affirmative(v,tense,c.subject,true),target=Grammar[kind](v,tense,c.subject,true);
    const rule=v.base==='be'?'BE does not use do / does / did. Move BE for questions and add NOT for negatives.':tense==='past'?'After DID / DID NOT, the main verb returns to the BASE FORM.':'Use DO / DOES in questions and negatives. The main verb stays in BASE FORM.';
    app.innerHTML=head('Grammar Lab',`Question ${i+1} / ${round.length}`)+`<div class="panel finalBox"><div class="labRule"><b>Rule:</b> ${escapeHtml(rule)}</div><span class="chip">${tense.toUpperCase()}</span><span class="chip">MAKE IT ${kind.toUpperCase()}</span><p class="sourceSentence">${escapeHtml(source)}</p><textarea id="labInput" class="sentenceInput" rows="3" placeholder="Write the ${kind} sentence"></textarea><button class="btn primary" onclick="checkGrammarLab()">Check grammar</button><div id="feed" class="feedback"></div></div>`;
    window.labRound={target,good:()=>good++,next:()=>{i++;render()}};$('#labInput').focus();
  }
  render();
}
function checkGrammarLab(){const r=window.labRound,input=$('#labInput');if(input.disabled)return;input.disabled=true;if(Grammar.sameSentence(input.value,r.target)){$('#feed').innerHTML=`Correct! <b>${escapeHtml(r.target)}</b>`;$('#feed').style.color='var(--green)';addXP(20);r.good()}else{$('#feed').innerHTML=`Correct form: <b>${escapeHtml(r.target)}</b>`;$('#feed').style.color='var(--red)';resetStreak()}setTimeout(r.next,1500)}

function memory(){
  const count=Math.min(state.level===3||state.level===0?6:5,pool().length),vs=sample(pool(),count),cards=shuffle(vs.flatMap(v=>[{id:v.id,label:v.base,kind:'base'},{id:v.id,label:Grammar.present(v,'She'),kind:'present'},{id:v.id,label:Grammar.past(v,'She'),kind:'past'}]));
  window.mem={open:[],done:0,count,moves:0};
  app.innerHTML=head('Memory Pro','Match THREE cards for each verb: base, present (she) and past.')+`<div class="panel"><div class="row"><span class="chip">Moves <b id="moves">0</b></span><span class="chip">Sets <b id="sets">0</b>/${count}</span></div><div class="memory memoryTriple">${cards.map((c,n)=>`<button class="mem" data-id="${c.id}" data-label="${escapeHtml(c.label)}" onclick="openMemory(this)">?</button>`).join('')}</div><div id="feed" class="feedback"></div></div>`;
}
function openMemory(button){const s=window.mem;if(button.classList.contains('open')||button.classList.contains('done')||s.open.length===3)return;button.classList.add('open');button.textContent=button.dataset.label;s.open.push(button);if(s.open.length===3){s.moves++;$('#moves').textContent=s.moves;const same=s.open.every(x=>x.dataset.id===s.open[0].dataset.id);if(same){s.open.forEach(x=>x.classList.add('done'));s.done++;$('#sets').textContent=s.done;addXP(8);s.open=[];if(s.done===s.count){$('#feed').textContent='Great! All verb families matched.';$('#feed').style.color='var(--green)'}}else setTimeout(()=>{s.open.forEach(x=>{x.classList.remove('open');x.textContent='?'});s.open=[]},700)}}

function robot(){
  const v=sample(pool(),1)[0],mode=Math.random()<.5?'past':'present',subject=mode==='present'?'She':'They',word=(mode==='past'?Grammar.past(v,subject):Grammar.present(v,subject)).toUpperCase(),letters=new Set();
  window.rob={v,mode,subject,word,letters,errors:0,max:2,over:false};
  app.innerHTML=head('Save the Robot','Only TWO wrong letters. The second mistake ends the round.')+`<div class="panel robot"><div class="robotBox"><div class="robotFace" id="face">🤖</div><div class="lives" id="lives">❤️ ❤️</div><div class="energy"><span id="energy"></span></div><p><b>2 ERRORS ONLY</b></p></div><div><span class="tenseBadge ${mode==='present'?'presentBadge':'pastBadge'}">${mode.toUpperCase()}</span><h2>${mode==='present'?`Present form for SHE: ${escapeHtml(v.base)}`:`Past form: ${escapeHtml(v.base)}`}</h2><p class="muted">${escapeHtml(v.meaning)}</p><div class="hangWord" id="hang"></div><div class="keyboard">${'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map(k=>`<button class="key" onclick="guessRobot(this,'${k}')">${k}</button>`).join('')}</div><div id="feed" class="feedback"></div><button id="robotNext" class="btn primary" style="display:none" onclick="robot()">Next verb</button></div></div>`;drawRobot();
}
function drawRobot(){const s=window.rob;$('#hang').innerHTML=s.word.split('').map(ch=>ch===' '?'<span style="width:18px"></span>':`<span class="hangLetter">${s.letters.has(ch)?ch:''}</span>`).join('');$('#energy').style.width=((s.max-s.errors)/s.max*100)+'%';$('#lives').textContent=s.errors===0?'❤️ ❤️':s.errors===1?'❤️ 🖤':'🖤 🖤';const solved=[...s.word].filter(ch=>/[A-Z]/.test(ch)).every(ch=>s.letters.has(ch));if(solved&&!s.over){s.over=true;$('#feed').textContent='Robot saved! '+s.word;$('#feed').style.color='var(--green)';$('#robotNext').style.display='inline-block';document.querySelectorAll('.key').forEach(k=>k.disabled=true);addXP(15)}else if(s.errors>=2&&!s.over){s.over=true;$('#face').textContent='🤖💤';$('#feed').textContent='Energy lost. Answer: '+s.word;$('#feed').style.color='var(--red)';$('#robotNext').style.display='inline-block';document.querySelectorAll('.key').forEach(k=>k.disabled=true);resetStreak()}}
function guessRobot(button,letter){const s=window.rob;if(s.over)return;button.disabled=true;s.letters.add(letter);if(!s.word.includes(letter))s.errors++;drawRobot()}

function matchGame(){
  const count=Math.min(8,pool().length),vs=sample(pool(),count),relationship=Math.random()<.5?'past':'present';const left=shuffle(vs),right=shuffle(vs);window.matchState={a:null,b:null,done:0,count,relationship};
  app.innerHTML=head('Match Rush',`Match BASE FORM with ${relationship==='past'?'PAST SIMPLE':'PRESENT for SHE'}.`)+`<div class="panel"><div class="row"><span class="chip">Matched <b id="matched">0</b>/${count}</span><span class="tenseBadge ${relationship==='past'?'pastBadge':'presentBadge'}">${relationship.toUpperCase()}</span></div><div class="matchBoard"><div class="matchCol" id="baseCol">${left.map(v=>`<button class="matchBtn" data-id="${v.id}" onclick="pickMatch(this,'a')">${escapeHtml(v.base)}</button>`).join('')}</div><div class="matchArrow">↔</div><div class="matchCol" id="formCol">${right.map(v=>`<button class="matchBtn" data-id="${v.id}" onclick="pickMatch(this,'b')">${escapeHtml(relationship==='past'?Grammar.past(v,'They'):Grammar.present(v,'She'))}</button>`).join('')}</div></div><div id="feed" class="feedback"></div></div>`;
}
function pickMatch(el,side){const s=window.matchState;if(el.classList.contains('done'))return;document.querySelectorAll((side==='a'?'#baseCol':'#formCol')+' .sel').forEach(x=>x.classList.remove('sel'));el.classList.add('sel');s[side]=el;if(s.a&&s.b){if(s.a.dataset.id===s.b.dataset.id){s.a.classList.add('done');s.b.classList.add('done');s.a.classList.remove('sel');s.b.classList.remove('sel');s.a=s.b=null;s.done++;$('#matched').textContent=s.done;addXP(8);if(s.done===s.count){$('#feed').textContent='All pairs matched!';$('#feed').style.color='var(--green)'}}else{$('#feed').textContent='Wrong pair. Try again.';$('#feed').style.color='var(--red)';resetStreak();setTimeout(()=>{s.a?.classList.remove('sel');s.b?.classList.remove('sel');s.a=s.b=null},450)}}}

function ladderGame(){
  const v=sample(pool(),1)[0];let step=0,points=0;const c=Grammar.context(v);const steps=[
    {label:'PRESENT (SHE)',answer:Grammar.present(v,'She'),choices:()=>sample(V.filter(x=>Grammar.present(x,'She')!==Grammar.present(v,'She')),3).map(x=>Grammar.present(x,'She'))},
    {label:'PAST SIMPLE',answer:Grammar.past(v,'They'),choices:()=>sample(V.filter(x=>Grammar.past(x,'They')!==Grammar.past(v,'They')),3).map(x=>Grammar.past(x,'They'))},
    {label:'PAST PARTICIPLE',answer:primaryParticiple(v),choices:()=>sample(V.filter(x=>primaryParticiple(x)!==primaryParticiple(v)),3).map(primaryParticiple)},
    {label:'SPANISH MEANING',answer:v.meaning,choices:()=>sample(V.filter(x=>x.meaning!==v.meaning),3).map(x=>x.meaning)},
    {label:'PAST SENTENCE',answer:Grammar.affirmative(v,'past',c.subject,true),choices:()=>sample(V.filter(x=>x.id!==v.id),3).map(x=>Grammar.affirmative(x,'past',Grammar.context(x).subject,true))}
  ];
  function render(){if(step>=steps.length){app.innerHTML=head('Verb Ladder')+`<div class="panel result"><div style="font-size:72px">🪜✨</div><div class="score">${points}/5</div><h2>${escapeHtml(v.base.toUpperCase())} → ${escapeHtml(v.past.toUpperCase())}</h2><button class="btn primary" onclick="ladderGame()">Another ladder</button></div>`;return}const st=steps[step],opts=shuffle([st.answer,...st.choices()]);app.innerHTML=head('Verb Ladder',`Step ${step+1} / 5 • One wrong answer sends you back to step 1.`)+`<div class="panel finalBox"><div class="ladder"><div class="ladderStep done"><span class="n">✓</span><div><small>BASE</small><b>${escapeHtml(v.base.toUpperCase())}</b></div></div>${steps.map((x,n)=>`<div class="ladderStep ${n<step?'done':''}"><span class="n">${n<step?'✓':n+1}</span><div><small>${escapeHtml(x.label)}</small><b>${n<step?escapeHtml(x.answer):'???'}</b></div></div>`).join('')}</div><h2>Choose: ${escapeHtml(st.label)}</h2><div class="options">${opts.map(o=>`<button class="option" style="text-transform:none" onclick="pickLadder(this,decodeURIComponent('${enc(o)}'),decodeURIComponent('${enc(st.answer)}'))">${escapeHtml(o)}</button>`).join('')}</div><div id="feed" class="feedback"></div></div>`;window.ladder={right:()=>{points++;step++;render()},wrong:()=>{step=0;points=0;setTimeout(render,900)}}}
  window.pickLadder=(button,answer,correct)=>{document.querySelectorAll('.option').forEach(x=>x.disabled=true);if(answer===correct){button.classList.add('ok');$('#feed').textContent='Correct! Keep climbing.';$('#feed').style.color='var(--green)';addXP(8);setTimeout(window.ladder.right,650)}else{button.classList.add('bad');$('#feed').textContent='Wrong. Back to step 1.';$('#feed').style.color='var(--red)';resetStreak();window.ladder.wrong()}};render();
}

let speedTimer=null;
function speedGame(){
  clearInterval(speedTimer);let left=45,correct=0,total=0,combo=0,current=null,mode=null,subject=null;
  function newPrompt(){current=sample(pool(),1)[0];mode=Math.random()<.5?'present':'past';subject=sample(Grammar.SUBJECTS,1)[0];const label=mode==='present'?`Present for ${subject}`:`Past simple`;$(`#speedLabel`).textContent=label;$('#speedBase').textContent=current.base;$('#speedMeaning').textContent=current.meaning;$('#speedEmoji').textContent=icon(current);$('#speedInput').value='';$('#speedInput').focus()}
  function finish(){clearInterval(speedTimer);app.innerHTML=head('Speed Run')+`<div class="panel result"><div style="font-size:72px">⚡</div><div class="score">${correct}</div><h2>correct answers in 45 seconds</h2><p>${total} attempts</p><button class="btn primary" onclick="speedGame()">Run again</button></div>`}
  app.innerHTML=head('Speed Run','Type present and past forms. Press Enter after each answer.')+`<div class="panel speedBox"><div class="timerRing" id="timerRing" style="--deg:360deg"><b id="time">45</b></div><div class="speedPrompt"><span id="speedLabel" class="tenseBadge presentBadge"></span><div class="combo">COMBO ×<span id="combo">0</span></div><div class="emoji" id="speedEmoji">⚡</div><h2 id="speedBase"></h2><p id="speedMeaning" class="muted"></p><input id="speedInput" class="answerInput bigInput" autocomplete="off" placeholder="Type the form"><div id="feed" class="feedback"></div><p><b id="speedCorrect">0</b> correct • <b id="speedTotal">0</b> attempts</p></div></div>`;
  window.speedState={answer(){const val=$('#speedInput').value.trim().toLowerCase();if(!val)return;const expected=mode==='present'?Grammar.present(current,subject):Grammar.past(current,subject);total++;if(val===expected.toLowerCase()){correct++;combo++;addXP(5+Math.min(combo,5));$('#feed').textContent='Correct!';$('#feed').style.color='var(--green)'}else{combo=0;resetStreak();$('#feed').textContent='Answer: '+expected;$('#feed').style.color='var(--red)'}$('#speedCorrect').textContent=correct;$('#speedTotal').textContent=total;$('#combo').textContent=combo;setTimeout(newPrompt,220)}};
  $('#speedInput').onkeydown=e=>{if(e.key==='Enter')window.speedState.answer()};newPrompt();speedTimer=setInterval(()=>{left--;$('#time').textContent=left;$('#timerRing').style.setProperty('--deg',(left/45*360)+'deg');if(left<=0)finish()},1000);
}

function finalGame(){
  const total=20;let i=0,good=0;const wrong=[];
  function render(){
    if(i>=total){const pct=Math.round(good/total*100);app.innerHTML=head('Final Challenge')+`<div class="panel result"><div style="font-size:72px">${pct>=90?'🏆':pct>=70?'⭐':'📘'}</div><div class="score">${good}/${total}</div><h2>${pct}% accuracy</h2><p class="muted">Present, past, sentence order and grammar transformations were included.</p>${wrong.length?`<div class="review">${wrong.slice(-8).map(x=>`<div><span>${escapeHtml(x.prompt)}</span><b>${escapeHtml(x.answer)}</b></div>`).join('')}</div>`:''}<button class="btn primary" onclick="finalGame()">Try again</button></div>`;return;}
    const type=i%5,v=sample(sentencePool(),1)[0],c=Grammar.context(v);let prompt='',answer='',body='';
    if(type===0){const tense=Math.random()<.5?'present':'past',subject=sample(Grammar.SUBJECTS,1)[0];answer=tense==='present'?Grammar.present(v,subject):Grammar.past(v,subject);prompt=`${tense} of ${v.base} for ${subject}`;body=`<span class="tenseBadge ${tense==='present'?'presentBadge':'pastBadge'}">${tense.toUpperCase()}</span><div class="finalBig">${escapeHtml(subject)} + ${escapeHtml(v.base)}</div><input id="finalInput" class="answerInput bigInput" placeholder="Type the verb form">`}
    else if(type===1){answer=Grammar.affirmative(v,'past',c.subject,true);prompt='Change to past';body=`<span class="tenseBadge presentBadge">PRESENT → PAST</span><p class="sourceSentence">${escapeHtml(Grammar.affirmative(v,'present',c.subject,true))}</p><textarea id="finalInput" class="sentenceInput" rows="3" placeholder="Write the past sentence"></textarea>`}
    else if(type===2){answer=Grammar.negative(v,'past',c.subject,true);prompt='Past negative';body=`<span class="chip">MAKE IT NEGATIVE</span><p class="sourceSentence">${escapeHtml(Grammar.affirmative(v,'past',c.subject,true))}</p><textarea id="finalInput" class="sentenceInput" rows="3" placeholder="Write the negative sentence"></textarea>`}
    else if(type===3){answer=Grammar.question(v,'present',c.subject,true);prompt='Present question';body=`<span class="chip">MAKE A QUESTION</span><p class="sourceSentence">${escapeHtml(Grammar.affirmative(v,'present',c.subject,true))}</p><textarea id="finalInput" class="sentenceInput" rows="3" placeholder="Write the question"></textarea>`}
    else{answer=primaryParticiple(v);prompt=`Participle of ${v.base}`;body=`<span class="chip">PAST PARTICIPLE</span><div class="finalBig">${escapeHtml(v.base)}</div><input id="finalInput" class="answerInput bigInput" placeholder="Type the participle">`}
    app.innerHTML=head('Final Challenge',`Question ${i+1} / ${total} • ${good} correct`)+`<div class="panel finalBox"><div class="progress"><span style="width:${i/total*100}%"></span></div><div style="height:18px"></div>${body}<div class="row" style="margin-top:14px"><button class="btn primary" onclick="checkFinal()">Check</button></div><div id="feed" class="feedback"></div></div>`;
    window.finalState={answer,prompt,type,right:()=>good++,wrong:()=>wrong.push({prompt,answer}),next:()=>{i++;render()}};const input=$('#finalInput');input.focus();input.onkeydown=e=>{if(e.key==='Enter'&&e.target.tagName!=='TEXTAREA')checkFinal()};
  }
  render();
}
function checkFinal(){const s=window.finalState,input=$('#finalInput');if(input.disabled)return;input.disabled=true;const ok=s.type===0||s.type===4?Grammar.normalize(input.value)===Grammar.normalize(s.answer):Grammar.sameSentence(input.value,s.answer);if(ok){$('#feed').textContent='Correct! +20 XP';$('#feed').style.color='var(--green)';s.right();addXP(20)}else{$('#feed').innerHTML=`Correct answer: <b>${escapeHtml(s.answer)}</b>`;$('#feed').style.color='var(--red)';s.wrong();resetStreak()}setTimeout(s.next,1300)}

function resultCard(good,total,pct,replay){return `<div class="panel result"><div style="font-size:72px">${pct>=90?'🏆':pct>=70?'⭐':'📚'}</div><div class="score">${good}/${total}</div><h2>${pct}% accuracy</h2><button class="btn primary" onclick="${replay}">Play again</button><button class="btn secondary" onclick="home()">Home</button></div>`}
